import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import LocationPicker from '../../components/LocationPicker';
import { complaintAPI, getImageUrl } from '../../services/api';
import { toast } from 'react-toastify';
import { apiErrorMessage } from '../../utils/notifications';
function EditComplaint() {
  const navigate = useNavigate(); const { id } = useParams();
  const [form, setForm] = useState({ complaintTitle: '', description: '', areaLocation: '', latitude: '', longitude: '' });
  const [image, setImage] = useState(null); const [preview, setPreview] = useState(''); const [existing, setExisting] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { complaintAPI.getById(id).then(({ data }) => { setForm({ complaintTitle: data.complaintTitle, description: data.description, areaLocation: data.areaLocation, latitude: data.latitude, longitude: data.longitude }); setExisting(data.complaintImage); }).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to load complaint.')).finally(() => setLoading(false)); }, [id]);
  const selectImage = (event) => { const file = event.target.files?.[0]; if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 5 * 1024 * 1024) return setError('Choose a JPG, PNG or WEBP image up to 5 MB.'); setImage(file); setPreview(URL.createObjectURL(file)); };
  const locate = () => navigator.geolocation ? navigator.geolocation.getCurrentPosition(({ coords }) => setForm((current) => ({ ...current, latitude: Number(coords.latitude.toFixed(7)), longitude: Number(coords.longitude.toFixed(7)) })), () => setError('Location permission was denied. Select the position on the map.')) : setError('Geolocation is not supported. Select the position on the map.');
  const submit = async (event) => { event.preventDefault(); setError(''); if (form.complaintTitle.trim().length < 5 || form.description.trim().length < 20 || form.areaLocation.trim().length < 3 || !form.latitude || !form.longitude) return setError('Complete the title, detailed description, landmark and verified map location.'); setLoading(true); try { const body = new FormData(); Object.entries(form).forEach(([key, value]) => body.append(key, value)); if (image) body.append('complaintImage', image); await complaintAPI.update(id, body); toast.success('Complaint updated and sent for reclassification.'); navigate(`/citizen/complaint/${id}`); } catch (requestError) { const message = apiErrorMessage(requestError, 'Complaint update failed.'); setError(message); toast.error(message); } finally { setLoading(false); } };
  if (loading && !form.complaintTitle) return <div className="loading-spinner"><div className="spinner-border text-primary" /></div>;
  return <><section className="dashboard-header premium-header"><div className="container"><span className="eyebrow">SAFE RECLASSIFICATION</span><h2><i className="bi bi-pencil-square me-2" />Edit pending complaint</h2><p className="mb-0">Changes rerun AI classification and operational routing automatically.</p></div></section><main className="container pb-5"><div className="row justify-content-center"><div className="col-xl-9"><form className="card-custom p-4 p-lg-5" onSubmit={submit}>{error && <div className="alert alert-danger">{error}</div>}<div className="row g-4"><div className="col-lg-7"><label className="form-label">Complaint title *</label><input className="form-control mb-3" value={form.complaintTitle} onChange={(e) => setForm({ ...form, complaintTitle: e.target.value })} maxLength="200" /><label className="form-label">Detailed description *</label><textarea className="form-control mb-3" rows="6" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} maxLength="3000" /><label className="form-label">Area / landmark *</label><input className="form-control mb-3" value={form.areaLocation} onChange={(e) => setForm({ ...form, areaLocation: e.target.value })} maxLength="255" /><label className="form-label">Replace evidence image</label><input type="file" className="form-control" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={selectImage} /><img className="complaint-image mt-3" src={preview || getImageUrl(existing)} alt="Complaint evidence preview" /></div><div className="col-lg-5"><div className="d-flex justify-content-between align-items-center"><label className="form-label">Verified location *</label><button type="button" className="btn btn-sm btn-outline-primary" onClick={locate}><i className="bi bi-crosshair me-1" />Use current GPS</button></div><LocationPicker latitude={Number(form.latitude)} longitude={Number(form.longitude)} onChange={(latitude, longitude) => setForm((current) => ({ ...current, latitude, longitude }))} /><div className="coordinate-chip mt-3"><span>Lat {form.latitude || '—'}</span><span>Lng {form.longitude || '—'}</span></div><div className="alert alert-info mt-3 small"><i className="bi bi-cpu me-2" />Citizens do not manually choose a department. AI classification and the active routing rule decide ownership.</div></div></div><div className="d-flex gap-3 mt-4"><button className="btn btn-primary-custom" disabled={loading}>{loading ? 'Updating...' : <><i className="bi bi-arrow-repeat me-2" />Update and reclassify</>}</button><button type="button" className="btn btn-outline-secondary" onClick={() => navigate('/citizen/my-complaints')}>Cancel</button></div></form></div></div></main></>;
}
export default EditComplaint;
