server:
  port: 8084

spring:
  application:
    name: email-notification-service

  profiles:
    active: local

  data:
    mongodb:
      uri: mongodb://localhost:27017/notification_db

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    listener:
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3
          multiplier: 2
          max-interval: 10000

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# -------------------------------------------------------
# Custom RabbitMQ Properties
# -------------------------------------------------------

rabbitmq:
  exchange:
    notification: kartyavya.events

  dead-letter-exchange:
    notification: kartyavya.events.dlx

  queue:
    report-created: email.report.created.q
    report-assigned: email.report.assigned.q
    report-status-changed: email.report.status.changed.q
    report-resolved: email.report.resolved.q

  routing-key:
    report-created: report.created
    report-assigned: report.assigned
    report-status-changed: report.status.changed
    report-resolved: report.resolved

# -------------------------------------------------------
# Email Configuration
# -------------------------------------------------------

email:
  from: ${EMAIL_FROM}

# -------------------------------------------------------
# Actuator
# -------------------------------------------------------

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

# -------------------------------------------------------
# Eureka
# -------------------------------------------------------

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# -------------------------------------------------------
# Logging
# -------------------------------------------------------

logging:
  level:
    root: INFO
    org.springframework.amqp: INFO
    org.springframework.mail: INFO
    org.springframework.data.mongodb: INFO
    com.kartyavya: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} : %msg%n"