server.port=8888

spring.application.name=config-server
spring.cloud.config.server.git.uri=https://github.com/navinchaudhari/kartyavya-config
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true

management.endpoints.web.exposure.include=health,info,refresh
